import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { io } from 'socket.io-client';
import { Stage, Layer, Rect, Text, Arrow, Line, Circle } from 'react-konva';
import { api } from './api.js';
import './styles.css';
import './styles-extra.css';

const API_ORIGIN = (import.meta.env.VITE_API_URL || 'http://localhost:5000/api').replace(/\/api$/, '');
const emptyLogin = { email: '', password: '', name: '' };

function App() {
  const [session, setSession] = useState(() => { const saved = localStorage.getItem('synctask_user'); return saved ? JSON.parse(saved) : null; });
  const [active, setActive] = useState(null);
  const socket = useMemo(() => session ? io(API_ORIGIN, { auth: { token: localStorage.getItem('synctask_token') } }) : null, [session]);
  useEffect(() => () => socket?.disconnect(), [socket]);
  const signOut = () => { localStorage.removeItem('synctask_token'); localStorage.removeItem('synctask_user'); setSession(null); setActive(null); };
  if (!session) return <Auth onAuth={setSession} />;
  return <WorkspaceList user={session.user} active={active} setActive={setActive} socket={socket} onSignOut={signOut} />;
}

function Auth({ onAuth }) {
  const [mode, setMode] = useState('login'); const [form, setForm] = useState(emptyLogin); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { const { data } = await api.post(`/auth/${mode === 'login' ? 'login' : 'register'}`, form); localStorage.setItem('synctask_token', data.token); localStorage.setItem('synctask_user', JSON.stringify(data)); onAuth(data); } catch (err) { setError(err.response?.data?.error || 'Could not continue'); } finally { setBusy(false); } }
  return <main className="auth-shell"><section className="auth-card"><div className="brand-mark">S</div><h1>SyncTask</h1><p>Tasks, quick calls, and shared thinking.</p><form onSubmit={submit}>{mode === 'register' && <label>Name<input required minLength="2" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label>}<label>Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Password<input required type="password" minLength="8" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label>{error && <p className="error">{error}</p>}<button disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'}</button></form><button className="link-button" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError(''); }}>{mode === 'login' ? 'New here? Create an account' : 'Already have an account? Sign in'}</button></section></main>;
}

function WorkspaceList({ user, active, setActive, socket, onSignOut }) {
  const [workspaces, setWorkspaces] = useState([]); const [name, setName] = useState(''); const [error, setError] = useState('');
  const refresh = async () => { try { setWorkspaces((await api.get('/workspaces')).data.workspaces); } catch { setError('Could not load workspaces'); } };
  useEffect(() => { refresh(); }, []);
  async function create(e) { e.preventDefault(); try { const { data } = await api.post('/workspaces', { name }); setName(''); await refresh(); setActive(data.workspace._id); } catch (err) { setError(err.response?.data?.error || 'Could not create workspace'); } }
  if (active) return <Workspace id={active} socket={socket} user={user} onBack={() => setActive(null)} />;
  return <main className="workspace-list"><header><div className="logo">SyncTask</div><div className="user-menu"><span>{user.name}</span><button className="ghost" onClick={onSignOut}>Sign out</button></div></header><section className="welcome"><p className="eyebrow">YOUR WORKSPACES</p><h1>Work together, clearly.</h1><p>Create a focused space for tasks, discussions, and quick diagrams.</p><form className="create-workspace" onSubmit={create}><input placeholder="e.g. Product launch" value={name} onChange={(e) => setName(e.target.value)} required minLength="2"/><button>Create workspace</button></form>{error && <p className="error">{error}</p>}</section><section className="workspace-grid">{workspaces.map((w) => <button className="workspace-card" key={w._id} onClick={() => setActive(w._id)}><span className="workspace-icon">{w.name[0].toUpperCase()}</span><span><strong>{w.name}</strong><small>{w.members.length} member{w.members.length !== 1 ? 's' : ''}</small></span><b>→</b></button>)}{!workspaces.length && <div className="empty">Your first workspace will appear here.</div>}</section></main>;
}

function Workspace({ id, socket, user, onBack }) {
  const [data, setData] = useState(null); const [tab, setTab] = useState('board'); const [selected, setSelected] = useState(null); const [callTask, setCallTask] = useState(null); const [inviteOpen, setInviteOpen] = useState(false); const [error, setError] = useState('');
  const load = async () => { try { setData((await api.get(`/workspaces/${id}`)).data); } catch (err) { setError(err.response?.data?.error || 'Could not load workspace'); } };
  useEffect(() => { load(); }, [id]);
  useEffect(() => { if (!socket || !data) return; socket.emit('workspace:join', { workspaceId: id }); const update = (event, fn) => socket.on(event, fn); update('task:created', (task) => setData((d) => ({ ...d, tasks: d.tasks.some((item) => item._id === task._id) ? d.tasks : [...d.tasks, task] }))); update('task:updated', (task) => setData((d) => ({ ...d, tasks: d.tasks.map((t) => t._id === task._id ? task : t) }))); update('task:moved', (task) => setData((d) => ({ ...d, tasks: d.tasks.map((t) => t._id === task._id ? task : t) }))); update('task:deleted', ({ id: taskId }) => setData((d) => ({ ...d, tasks: d.tasks.filter((t) => t._id !== taskId) }))); update('column:created', (column) => setData((d) => ({ ...d, columns: d.columns.some((item) => item._id === column._id) ? d.columns : [...d.columns, column] }))); return () => ['task:created','task:updated','task:moved','task:deleted','column:created'].forEach((e) => socket.off(e)); }, [socket, data?.workspace?._id]);
  const addTask = (task) => setData((d) => ({ ...d, tasks: d.tasks.some((item) => item._id === task._id) ? d.tasks : [...d.tasks, task] }));
  const updateTask = (task) => setData((d) => ({ ...d, tasks: d.tasks.map((t) => t._id === task._id ? task : t) }));
  if (!data) return <main className="loading">{error || 'Loading workspace…'}</main>;
  const isOwner = data.workspace.ownerId === user.id || data.workspace.members.find((m) => String(m.userId) === user.id)?.role === 'owner';
  return <main className="workspace"><header className="workspace-header"><button className="back" onClick={onBack}>← Workspaces</button><div><p className="eyebrow">WORKSPACE</p><h1>{data.workspace.name}</h1></div><div className="header-actions"><span className="member-count">◉ {data.workspace.members.length} member{data.workspace.members.length !== 1 ? 's' : ''}</span>{isOwner && <button className="ghost" onClick={() => setInviteOpen(true)}>Invite</button>}</div></header><nav className="tabs"><button className={tab === 'board' ? 'active' : ''} onClick={() => setTab('board')}>▦ Board</button><button className={tab === 'whiteboard' ? 'active' : ''} onClick={() => setTab('whiteboard')}>✦ Whiteboard</button></nav>{tab === 'board' ? <Board data={data} onTask={addTask} onUpdate={updateTask} select={setSelected} /> : <Whiteboard workspaceId={id} initial={data.whiteboard?.elements || []} socket={socket} isOwner={isOwner} />}{selected && <TaskDetails task={selected} workspace={data.workspace} user={user} onClose={() => setSelected(null)} onUpdate={(task) => { updateTask(task); setSelected(task); }} onCall={() => setCallTask(selected)} />}{inviteOpen && <Invite workspaceId={id} onClose={() => setInviteOpen(false)} onDone={load} />}{callTask && <CallRoom workspaceId={id} task={callTask} socket={socket} onClose={() => setCallTask(null)} />}</main>;
}

function Board({ data, onTask, onUpdate, select }) {
  const [adding, setAdding] = useState(null); const [newColumn, setNewColumn] = useState(false);
  async function move(taskId, columnId) { try { const { data: response } = await api.patch(`/workspaces/tasks/${taskId}/move`, { columnId, position: Date.now() }); onUpdate(response.task); } catch (err) { alert(err.response?.data?.error || 'Could not move task'); } }
  async function addColumn(name) { try { await api.post(`/workspaces/${data.workspace._id}/columns`, { name }); setNewColumn(false); } catch (err) { alert(err.response?.data?.error || 'Could not add column'); } }
  return <section className="board">{data.columns.map((column) => <div className="column" key={column._id} onDragOver={(e) => e.preventDefault()} onDrop={(e) => move(e.dataTransfer.getData('taskId'), column._id)}><div className="column-title"><strong>{column.name}</strong><span>{data.tasks.filter((t) => String(t.columnId) === column._id).length}</span></div><div className="task-stack">{data.tasks.filter((task) => String(task.columnId) === column._id).sort((a,b) => a.position - b.position).map((task) => <TaskCard task={task} key={task._id} select={select} />)}</div>{adding === column._id ? <TaskCreator columnId={column._id} workspace={data.workspace} onDone={(task) => { onTask(task); setAdding(null); }} onCancel={() => setAdding(null)} /> : <button className="add-task" onClick={() => setAdding(column._id)}>+ Add task</button>}</div>)}<div className="column add-column">{newColumn ? <InlineName placeholder="Column name" onDone={addColumn} onCancel={() => setNewColumn(false)} /> : <button className="add-task" onClick={() => setNewColumn(true)}>+ Add column</button>}</div></section>;
}

function TaskCard({ task, select }) { return <article className="task-card" draggable onDragStart={(e) => e.dataTransfer.setData('taskId', task._id)} onClick={() => select(task)}><div className={`priority-dot ${task.priority}`}></div><strong>{task.title}</strong>{task.description && <p>{task.description}</p>}<footer><span className={`priority ${task.priority}`}>{task.priority}</span>{task.assigneeId?.name && <span className="avatar" title={task.assigneeId.name}>{task.assigneeId.name[0]}</span>}</footer></article>; }
function TaskCreator({ columnId, workspace, onDone, onCancel }) { const [title, setTitle] = useState(''); const [busy, setBusy] = useState(false); async function submit(e) { e.preventDefault(); setBusy(true); try { const { data } = await api.post(`/workspaces/${workspace._id}/tasks`, { title, columnId }); onDone(data.task); } catch (err) { alert(err.response?.data?.error || 'Could not create task'); } finally { setBusy(false); } } return <form className="quick-form" onSubmit={submit}><input autoFocus placeholder="Task title" value={title} onChange={(e) => setTitle(e.target.value)} required/><div><button disabled={busy}>Add</button><button type="button" className="ghost" onClick={onCancel}>Cancel</button></div></form>; }
function InlineName({ placeholder, onDone, onCancel }) { const [name, setName] = useState(''); return <form className="quick-form" onSubmit={(e) => { e.preventDefault(); onDone(name); }}><input autoFocus placeholder={placeholder} value={name} onChange={(e) => setName(e.target.value)} required/><div><button>Add</button><button type="button" className="ghost" onClick={onCancel}>Cancel</button></div></form>; }

function TaskDetails({ task, workspace, user, onClose, onUpdate, onCall }) {
  const [details, setDetails] = useState(null); const [comment, setComment] = useState(''); const [editing, setEditing] = useState(false); const [form, setForm] = useState({ title: task.title, description: task.description || '', priority: task.priority, assigneeId: task.assigneeId?._id || '' });
  const load = async () => { const { data } = await api.get(`/workspaces/tasks/${task._id}/details`); setDetails(data); };
  useEffect(() => { load(); }, [task._id]);
  async function save(e) { e.preventDefault(); const { data } = await api.patch(`/workspaces/tasks/${task._id}`, { ...form, assigneeId: form.assigneeId || null }); onUpdate(data.task); setEditing(false); }
  async function addComment(e) { e.preventDefault(); if (!comment.trim()) return; await api.post(`/workspaces/tasks/${task._id}/comments`, { text: comment }); setComment(''); load(); }
  return <div className="modal-backdrop"><aside className="task-detail"><button className="close" onClick={onClose}>×</button>{editing ? <form className="detail-form" onSubmit={save}><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required/><textarea value={form.description} placeholder="Add a description" onChange={(e) => setForm({ ...form, description: e.target.value })}/><select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}><option value="low">Low priority</option><option value="medium">Medium priority</option><option value="high">High priority</option></select><select value={form.assigneeId} onChange={(e) => setForm({ ...form, assigneeId: e.target.value })}><option value="">Unassigned</option>{workspace.members.map((m) => <MemberOption key={m._id} member={m} />)}</select><button>Save changes</button></form> : <><span className={`priority ${task.priority}`}>{task.priority} priority</span><h2>{task.title}</h2><p className="description">{task.description || 'No description yet.'}</p><div className="detail-actions"><button onClick={() => setEditing(true)}>Edit task</button><button className="secondary" onClick={onCall}>◉ Start call</button></div></>}<section className="comments"><h3>Discussion</h3>{details?.comments.map((c) => <article className="comment" key={c._id}><span className="avatar">{c.authorId.name[0]}</span><div><strong>{c.authorId.name}</strong><p>{c.text}</p></div></article>)}<form onSubmit={addComment}><input placeholder="Write a comment…" value={comment} onChange={(e) => setComment(e.target.value)} /><button>Send</button></form></section><section className="activity"><h3>Activity</h3>{details?.activity.map((a) => <p key={a._id}><b>{a.actorId?.name || 'Someone'}</b> {humanActivity(a.type)} <small>{new Date(a.createdAt).toLocaleString()}</small></p>)}</section></aside></div>;
}
function MemberOption({ member }) { const id = member.userId?._id || member.userId; const name = member.userId?.name || 'Member'; return <option value={id}>{name} ({member.role})</option>; }
function humanActivity(type) { return ({ task_created: 'created this task', task_updated: 'updated this task', task_moved: 'moved this task', comment_added: 'commented', call_started: 'started a call', call_ended: 'ended a call' })[type] || type.replaceAll('_', ' '); }

function Invite({ workspaceId, onClose, onDone }) { const [email, setEmail] = useState(''); const [error, setError] = useState(''); async function submit(e) { e.preventDefault(); try { await api.post(`/workspaces/${workspaceId}/invite`, { email }); onDone(); onClose(); } catch (err) { setError(err.response?.data?.error || 'Could not invite user'); } } return <div className="modal-backdrop"><div className="small-modal"><button className="close" onClick={onClose}>×</button><h2>Invite teammate</h2><p>They must already have a SyncTask account.</p><form onSubmit={submit}><input type="email" placeholder="teammate@example.com" value={email} onChange={(e) => setEmail(e.target.value)} required/>{error && <p className="error">{error}</p>}<button>Invite member</button></form></div></div>; }

const colors = ['#f9d95d', '#f8a4a8', '#9fd8cb', '#a9c9ff', '#d3b5ff'];
function Whiteboard({ workspaceId, initial, socket, isOwner }) {
  const [elements, setElements] = useState(initial); const [tool, setTool] = useState('select'); const [color, setColor] = useState(colors[0]); const [cursors, setCursors] = useState({}); const [selectedId, setSelectedId] = useState(null); const [viewport, setViewport] = useState({ x: 0, y: 0, scale: 1 }); const stageRef = useRef(null); const drawing = useRef(null); const timer = useRef(null);
  useEffect(() => { setElements(initial); }, [workspaceId]);
  const persist = (next) => { clearTimeout(timer.current); timer.current = setTimeout(() => api.put(`/workspaces/${workspaceId}/whiteboard`, { elements: next }).catch(console.error), 450); };
  const commit = (next) => { setElements(next); persist(next); };
  useEffect(() => { if (!socket) return; const update = ({ elements }) => setElements(elements); const cursor = (c) => setCursors((old) => ({ ...old, [c.userId]: c })); socket.on('whiteboard:updated', update); socket.on('whiteboard:cursor', cursor); return () => { socket.off('whiteboard:updated', update); socket.off('whiteboard:cursor', cursor); }; }, [socket]);
  const pointer = () => { const point = stageRef.current.getPointerPosition(); return point ? { x: (point.x - viewport.x) / viewport.scale, y: (point.y - viewport.y) / viewport.scale } : null; };
  function start(e) { const p = pointer(); if (!p || tool === 'select' || tool === 'pan') return; let element; const id = crypto.randomUUID(); if (tool === 'pencil') element = { id, type: 'freeDraw', points: [p.x, p.y], color, strokeWidth: 3 }; else if (tool === 'sticky') element = { id, type: 'stickyNote', x: p.x, y: p.y, width: 190, height: 120, color, content: 'New idea' }; else if (tool === 'text') element = { id, type: 'text', x: p.x, y: p.y, color: '#172033', content: 'Text' }; else element = { id, type: tool, x: p.x, y: p.y, width: 2, height: 2, color };
    drawing.current = element; setElements((old) => [...old, element]);
  }
  function move(e) { const p = pointer(); if (p) socket?.emit('whiteboard:cursor', { workspaceId, cursor: p }); if (!drawing.current || !p) return; const nextElement = { ...drawing.current }; if (nextElement.type === 'freeDraw') nextElement.points = [...nextElement.points, p.x, p.y]; else if (nextElement.type === 'arrow') { nextElement.points = [nextElement.x, nextElement.y, p.x, p.y]; } else { nextElement.width = p.x - nextElement.x; nextElement.height = p.y - nextElement.y; } drawing.current = nextElement; setElements((old) => old.map((x) => x.id === nextElement.id ? nextElement : x)); }
  function finish() { if (!drawing.current) return; const final = drawing.current; drawing.current = null; setElements((old) => { const next = old.map((x) => x.id === final.id ? final : x); persist(next); return next; }); }
  function transform(id, attrs) { setElements((old) => { const next = old.map((x) => x.id === id ? { ...x, ...attrs } : x); persist(next); return next; }); }
  function editText(id) { const element = elements.find((item) => item.id === id); if (!element || !['stickyNote', 'text'].includes(element.type)) return; const content = window.prompt('Text', element.content); if (content !== null) transform(id, { content: content.slice(0, 500) }); }
  function removeSelected() { if (!selectedId) return; setElements((old) => { const next = old.filter((item) => item.id !== selectedId); persist(next); return next; }); setSelectedId(null); }
  async function clear() { if (confirm('Clear the shared whiteboard for everyone?')) await api.delete(`/workspaces/${workspaceId}/whiteboard`); }
  return <section className="whiteboard"><aside className="toolbar"><button className={tool === 'select' ? 'selected' : ''} onClick={() => setTool('select')} title="Select">↖</button><button className={tool === 'pan' ? 'selected' : ''} onClick={() => setTool('pan')} title="Pan canvas">✥</button><button className={tool === 'pencil' ? 'selected' : ''} onClick={() => setTool('pencil')} title="Pencil">✎</button><button className={tool === 'sticky' ? 'selected' : ''} onClick={() => setTool('sticky')} title="Sticky note">▣</button><button className={tool === 'text' ? 'selected' : ''} onClick={() => setTool('text')} title="Text">T</button><button className={tool === 'rectangle' ? 'selected' : ''} onClick={() => setTool('rectangle')} title="Rectangle">□</button><button className={tool === 'arrow' ? 'selected' : ''} onClick={() => setTool('arrow')} title="Arrow">→</button><button disabled={!selectedId} onClick={removeSelected} title="Delete selected item">×</button><hr/>{colors.map((c) => <button aria-label={c} key={c} className={`color ${color === c ? 'selected' : ''}`} style={{ background: c }} onClick={() => setColor(c)}/>)}</aside><div className="canvas-wrap"><Stage ref={stageRef} width={window.innerWidth - 70} height={window.innerHeight - 185} x={viewport.x} y={viewport.y} scaleX={viewport.scale} scaleY={viewport.scale} draggable={tool === 'pan'} onDragEnd={(e) => setViewport((v) => ({ ...v, x: e.target.x(), y: e.target.y() }))} onWheel={(e) => { e.evt.preventDefault(); setViewport((v) => ({ ...v, scale: Math.max(.5, Math.min(1.7, v.scale + (e.evt.deltaY > 0 ? -.1 : .1))) })); }} onMouseDown={start} onMousemove={move} onMouseUp={finish}><Layer>{elements.map((el) => <CanvasElement key={el.id} el={el} selectable={tool === 'select'} selected={selectedId === el.id} onSelect={setSelectedId} onEdit={editText} onTransform={transform}/>)}{Object.values(cursors).map((c) => <React.Fragment key={c.userId}><Circle x={c.cursor.x} y={c.cursor.y} radius={5} fill="#5d5fef"/><Text x={c.cursor.x + 8} y={c.cursor.y + 8} text={c.name} fontSize={12} fill="#5d5fef"/></React.Fragment>)}</Layer></Stage></div>{isOwner && <button className="clear-board" onClick={clear}>Clear board</button>}</section>;
}
function CanvasElement({ el, selectable, selected, onSelect, onEdit, onTransform }) { const common = { draggable: selectable, onClick: () => selectable && onSelect(el.id), onTap: () => selectable && onSelect(el.id), onDragEnd: (e) => onTransform(el.id, { x: e.target.x(), y: e.target.y() }) }; const selectedStyle = selected ? { shadowColor: '#5d5fef', shadowBlur: 10, shadowOpacity: .65 } : {}; if (el.type === 'freeDraw') return <Line {...common} points={el.points} stroke={el.color} strokeWidth={el.strokeWidth} lineCap="round" lineJoin="round"/>; if (el.type === 'arrow') return <Arrow {...common} points={el.points || [el.x,el.y,el.x+el.width,el.y+el.height]} stroke={el.color} fill={el.color} pointerLength={8} pointerWidth={8} strokeWidth={3}/>; if (el.type === 'rectangle') return <Rect {...common} {...selectedStyle} x={el.x} y={el.y} width={el.width} height={el.height} stroke={el.color} strokeWidth={3} cornerRadius={4}/>; if (el.type === 'stickyNote') return <><Rect {...common} {...selectedStyle} onDblClick={() => onEdit(el.id)} onDblTap={() => onEdit(el.id)} x={el.x} y={el.y} width={el.width} height={el.height} fill={el.color} shadowBlur={5} cornerRadius={4}/><Text {...common} onDblClick={() => onEdit(el.id)} onDblTap={() => onEdit(el.id)} x={el.x + 12} y={el.y + 12} text={el.content} width={el.width - 24} fontSize={16} fill="#1d2637"/></>; return <Text {...common} {...selectedStyle} onDblClick={() => onEdit(el.id)} onDblTap={() => onEdit(el.id)} x={el.x} y={el.y} text={el.content} fontSize={20} fill={el.color}/>; }

function CallRoom({ workspaceId, task, socket, onClose }) {
  const localRef = useRef(null); const remoteRef = useRef(null); const peerRef = useRef(null); const streamRef = useRef(null); const [status, setStatus] = useState('Connecting to your camera…'); const [muted, setMuted] = useState(false); const [cameraOff, setCameraOff] = useState(false);
  useEffect(() => { let alive = true;
    async function setup() { try { const stream = await navigator.mediaDevices.getUserMedia({ video: { width: { ideal: 640 }, height: { ideal: 480 }, frameRate: { ideal: 18, max: 20 } }, audio: true }); if (!alive) return; streamRef.current = stream; localRef.current.srcObject = stream; socket.emit('call:join', { workspaceId, taskId: task._id }, async (reply) => { if (reply?.error) { setStatus(reply.error); return; } setStatus(reply.peers.length ? 'Connecting…' : 'Waiting for another teammate to join'); if (reply.peers[0]) await createOffer(reply.peers[0]); }); } catch { setStatus('Camera or microphone access was not granted.'); } }
    const createPeer = (targetId) => { if (peerRef.current) peerRef.current.close(); const pc = new RTCPeerConnection({ iceServers: [{ urls: 'stun:stun.l.google.com:19302' }] }); peerRef.current = pc; streamRef.current?.getTracks().forEach((track) => pc.addTrack(track, streamRef.current)); pc.ontrack = (event) => { remoteRef.current.srcObject = event.streams[0]; setStatus('Connected'); }; pc.onicecandidate = (event) => { if (event.candidate) socket.emit('webrtc:ice-candidate', { taskId: task._id, targetId, candidate: event.candidate }); }; pc.onconnectionstatechange = () => { if (pc.connectionState === 'disconnected' || pc.connectionState === 'failed') setStatus('Call disconnected'); }; return pc; };
    const createOffer = async (targetId) => { const pc = createPeer(targetId); const offer = await pc.createOffer(); await pc.setLocalDescription(offer); socket.emit('webrtc:offer', { taskId: task._id, targetId, offer }); };
    const joined = ({ socketId }) => createOffer(socketId);
    const offer = async ({ fromId, offer }) => { const pc = createPeer(fromId); await pc.setRemoteDescription(offer); const answer = await pc.createAnswer(); await pc.setLocalDescription(answer); socket.emit('webrtc:answer', { taskId: task._id, targetId: fromId, answer }); };
    const answer = async ({ answer }) => { if (peerRef.current) await peerRef.current.setRemoteDescription(answer); };
    const candidate = async ({ candidate }) => { try { await peerRef.current?.addIceCandidate(candidate); } catch {} };
    const left = () => { remoteRef.current.srcObject = null; peerRef.current?.close(); peerRef.current = null; setStatus('Your teammate left. Waiting for someone to join.'); };
    socket.on('call:user-joined', joined); socket.on('webrtc:offer', offer); socket.on('webrtc:answer', answer); socket.on('webrtc:ice-candidate', candidate); socket.on('call:user-left', left); setup();
    return () => { alive = false; socket.emit('call:leave'); ['call:user-joined','webrtc:offer','webrtc:answer','webrtc:ice-candidate','call:user-left'].forEach((e) => socket.off(e)); peerRef.current?.close(); streamRef.current?.getTracks().forEach((t) => t.stop()); };
  }, [task._id]);
  const toggleMute = () => { streamRef.current?.getAudioTracks().forEach((t) => t.enabled = !t.enabled); setMuted((x) => !x); };
  const toggleCamera = () => { streamRef.current?.getVideoTracks().forEach((t) => t.enabled = !t.enabled); setCameraOff((x) => !x); };
  return <div className="modal-backdrop"><section className="call-room"><header><div><p className="eyebrow">TASK DISCUSSION</p><h2>{task.title}</h2></div><button className="close" onClick={onClose}>×</button></header><p className="call-status"><i></i>{status}</p><div className="videos"><video ref={remoteRef} autoPlay playsInline className="remote-video"/><div className="local-video-wrap"><video ref={localRef} autoPlay muted playsInline className="local-video"/>{cameraOff && <span>Camera off</span>}</div></div><footer className="call-controls"><button onClick={toggleMute}>{muted ? 'Unmute' : 'Mute'}</button><button onClick={toggleCamera}>{cameraOff ? 'Turn camera on' : 'Turn camera off'}</button><button className="danger" onClick={onClose}>Leave call</button></footer></section></div>;
}

createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>);
